modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/DN2048/XaeroMap-CreateMod-Train-Map"
issueTrackerURL="https://github.com/DN2048/XaeroMap-CreateMod-Train-Map/issues"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#logoFile="examplemod.png"
credits='''${mod_credits}'''
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="xaeroworldmap"
    mandatory=true
    versionRange="${xaero_world_map_version_range}"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="create"
    mandatory=true
    versionRange="${create_version_range}"
    ordering="NONE"
    side="CLIENT"